// Configuración local de GeoHogar - EJEMPLO
window.CONFIG = {
    GEMINI_API_KEY_1: "YOUR_GEMINI_API_KEY_1_HERE",
    GEMINI_API_KEY_2: "YOUR_GEMINI_API_KEY_2_HERE",
    FIREBASE_API_KEY: "YOUR_FIREBASE_API_KEY_HERE"
};
